apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
  namespace: frontend
  annotations:
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - 18.222.189.251
    secretName: mysecret
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  websvc
                port:
                  number: 80
          - path: /login
            pathType: Prefix
            backend:
              service:
                name:  websvc
                port:
                  number: 80
          - path: /puffersoft
            pathType: Prefix
            backend:
              service:
                name:  websvc
                port:
                  number: 80
