apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
  namespace: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.dreggystore.com
    secretName: example-tls
  rules:
    - host: www.dreggystore.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  websvc
                port:
                  number: 80
          - path: /login
            pathType: Prefix
            backend:
              service:
                name:  websvc
                port:
                  number: 80
          - path: /puffersoft
            pathType: Prefix
            backend:
              service:
                name:  websvc
                port:
                  number: 80
