apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
  namespace: prom
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: controller-traefik
  rules:
   - http:
        paths:
          - path: /prom
            pathType: Prefix
            backend:
              service:
                name:  prom-prometheus-server
                port:
                  number: 80
